openapi: 3.0.0
paths:
  /healthz:
    get:
      operationId: HealthzController_checkHealth
      summary: Executes Health Check
      description: >-
        Runs a health check on the service and its dependencies, including
        upstream services
      parameters: []
      responses:
        '200':
          description: The Health Check is successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  info:
                    type: object
                    example:
                      database:
                        status: up
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
                    nullable: true
                  error:
                    type: object
                    example: {}
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
                    nullable: true
                  details:
                    type: object
                    example:
                      database:
                        status: up
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
        '503':
          description: The Health Check is not successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  info:
                    type: object
                    example:
                      database:
                        status: up
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
                    nullable: true
                  error:
                    type: object
                    example:
                      redis:
                        status: down
                        message: Could not connect
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
                    nullable: true
                  details:
                    type: object
                    example:
                      database:
                        status: up
                      redis:
                        status: down
                        message: Could not connect
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
      tags:
        - Health Check
  /healthz/self:
    get:
      operationId: HealthzController_checkSelfHealth
      summary: Executes Self Health Check
      description: >-
        Runs a health check on the service and its core dependencies, exclusing
        upstream services
      parameters: []
      responses:
        '200':
          description: The Health Check is successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  info:
                    type: object
                    example:
                      database:
                        status: up
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
                    nullable: true
                  error:
                    type: object
                    example: {}
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
                    nullable: true
                  details:
                    type: object
                    example:
                      database:
                        status: up
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
        '503':
          description: The Health Check is not successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  info:
                    type: object
                    example:
                      database:
                        status: up
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
                    nullable: true
                  error:
                    type: object
                    example:
                      redis:
                        status: down
                        message: Could not connect
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
                    nullable: true
                  details:
                    type: object
                    example:
                      database:
                        status: up
                      redis:
                        status: down
                        message: Could not connect
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
      tags:
        - Health Check
  /events/{aggregateId}:
    get:
      operationId: AggregateEventsController_getByAggregateId
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AggregateEvent'
      tags:
        - Events
  /v1/me/videos:
    post:
      operationId: CreateVideoController_execute
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateVideoInput'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateVideoOutput'
      tags:
        - Video
    get:
      operationId: ListMyVideosController_execute
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ListMyVideosOutput'
      tags:
        - Video
  /v1/me/videos/{id}:
    get:
      operationId: GetMyVideoController_execute
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMyVideoOutput'
      tags:
        - Video
  /v1/me/videos/{id}/download:
    get:
      operationId: DownloadMyContentController_execute
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
        - name: target
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DownloadMyContentOutput'
      tags:
        - Video
info:
  title: FiapXApi
  description: API Component for Fiap X
  version: v1.0.0-development
  contact: {}
tags: []
servers:
  - url: http://localhost:3000
    description: development
components:
  schemas:
    AggregateEvent:
      type: object
      properties:
        id:
          type: string
        aggregateId:
          type: string
        eventName:
          type: string
        timestamp:
          format: date-time
          type: string
        version:
          type: number
        data:
          type: object
          description: The internal domain event structure
      required:
        - id
        - aggregateId
        - eventName
        - timestamp
        - version
        - data
    CreateVideoInput:
      type: object
      properties:
        filename:
          type: string
        snapshotIntervalInSeconds:
          type: number
      required:
        - filename
    CreateVideoOutput:
      type: object
      properties:
        id:
          type: string
        signedUrlForUpload:
          type: string
      required:
        - id
        - signedUrlForUpload
    GetMyVideoOutput:
      type: object
      properties:
        id:
          type: string
        filename:
          type: string
        status:
          type: string
          enum:
            - PENDING
            - PROCESSED
            - FAILED
        snapshotIntervalInSeconds:
          type: number
        videoPath:
          type: string
        zipPath:
          type: string
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
      required:
        - id
        - filename
        - status
        - snapshotIntervalInSeconds
        - videoPath
        - zipPath
        - createdAt
        - updatedAt
    ListMyVideosOutput:
      type: object
      properties:
        id:
          type: string
        filename:
          type: string
        status:
          type: string
          enum:
            - PENDING
            - PROCESSED
            - FAILED
        snapshotIntervalInSeconds:
          type: number
        videoPath:
          type: string
        zipPath:
          type: string
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
      required:
        - id
        - filename
        - status
        - snapshotIntervalInSeconds
        - videoPath
        - zipPath
        - createdAt
        - updatedAt
    DownloadMyContentOutput:
      type: object
      properties:
        downloadSignedUrl:
          type: string
      required:
        - downloadSignedUrl
externalDocs:
  description: Export Specs
  url: /docs-json
